# On SLE4 we need to load the modules in a certain order, so let's block
# the following modules from automatic loading.
blacklist glink_pkt
blacklist glink_probe
blacklist qrtr-smd
blacklist qcom_q6v5_pas
blacklist qcom_pil_info
blacklist qcom_q6v5
blacklist qcom_sysmon
blacklist pci_msm_drv
blacklist slim_qcom_ngd_ctrl
blacklist rproc_qcom_common
blacklist qcom_smd
blacklist cdsp_loader
blacklist icnss2
blacklist wlan_firmware_service
blacklist cnss_prealloc
blacklist wlan
