altmode-glink
bam_dma
bcl_pmic5
bcl_soc
boot_stats
cdsp-loader
cdsprm
cfg80211
charger-ulog-glink
clk-spmi-pmic-div
core_hang_detect
coresight-csr
coresight-cti
coresight-dummy
coresight-etm4x
coresight-funnel
coresight-hwevent
coresight
coresight-remote-etm
coresight-replicator
coresight-stm
coresight-tgu
coresight-tmc
coresight-tpda
coresight-tpdm
cpufreq_ondemand
cpufreq_userspace
cx_ipeak
dwc3-msm
ehset
eud
f_fs_ipc_log
frpc-adsprpc
glink_pkt
glink_probe
heap_mem_ext_v01
i2c-dev
i2c-msm-geni
i2c-qcom-geni
icc-test
ipa_fmwk
leds-qpnp-flash-v2
leds-qpnp-vibrator-ldo
leds-qti-flash
leds-qti-tri-led
lmh_cpu_vdd_cdev
memlat
msm_geni_serial
msm_gpi
msm_lmh_dcvs
msm_memshare
msm_performance
msm_qmp
msm_sharedmem
msm-tsens-driver
panel_event_notifier
pdr_interface
phy-generic
phy-msm-qusb
phy-msm-qusb-v2
phy-msm-snps-hs
phy-msm-ssusb-qmp
phy-qcom-emu
phy-xgene
pinctrl-spmi-mpp
pmic_glink
pwm-qti-lpg
qcom-i2c-pmic
qcom_iommu_debug
qcom_pil_info
qcom_pm8008-regulator
qcom_q6v5
qcom_q6v5_pas
qcom-qpnp-qg
qcom_ramdump
qcom-smb1355-charger
qcom-smb1390-charger
qcom_smd
qcom-spmi-adc5
qcom-spmi-adc-tm5
qcom-spmi-temp-alarm
qcom_sysmon
qcom_tsens
qcom-vadc-common
qmi_helpers
qpnp-lcdb-regulator
qpnp-misc
qpnp-pbs
qpnp-revid
qpnp-smb5-main
qrtr-smd
qseecom_proxy
qti_battery_debug
qti_cpufreq_cdev
qti_devfreq_cdev
qti_qmi_cdev
qti_qmi_sensor
refgen
regulator_cdev
rpm_master_stat
rpm_smd_cooling_device
rpm-smd-debug
rproc_qcom_common
rq_stats
SGM7220
slimbus
slim-qcom-ngd-ctrl
smp2p
smp2p_sleepstate
soc_sleep_stats
spidev
spi-geni-qcom
spi-msm-geni
sps_drv
stm_core
stm_ftrace
subsystem_sleep_stats
sysmon_subsystem_stats
thermal_pause
ucsi_glink
usb_bam
usb_f_ccid
usb_f_cdev
usb_f_diag
usb_f_gsi
usb_f_qdss
zram
zsmalloc
