#!/bin/bash

PARSE_PKGS=./tools/parse-pkgs.sh

get_deps() {
    deps=$(sed '/^#/d' < "$1" | grep "FROM lfedge" | awk '{print $2}' | cut -d":" -f1 | sed -e "/.*eve-alpine.*/d" -e "/.*eve-kernel.*/d")
    for d in $deps; do
        #shellcheck disable=SC2001
        dockfile=$(echo "$d" | sed 's#^lfedge/\(eve-\|\)\(.*\)#pkg/\2/Dockerfile#')
        if [ -e "$dockfile" ]; then
            get_deps "$dockfile"
        else
            echo "ERROR: $dockfile not found."
            break
        fi
    done
    # There is no more dependencies, just print the name of the package
    dirname "$1"
}

print_head() {
    if [ "$1" = "IMG" ]; then
        cat << EOF
digraph unix {
  rankdir="LR";
EOF
    else
        cat << EOF
#
# This file was generated by EVE's build system. DO NOT EDIT.
#
EOF
    fi
}

print_single_dep() {
    if [ "$1" = "IMG" ]; then
        echo "\"$pkg\";"
    fi
}

print_dep() {
    if [ "$1" = "IMG" ]; then
        echo "\"$2\" -> \"$3\";"
    else
        echo "$2: $3"
    fi
}

print_tail() {
    if [ "$1" = "IMG" ]; then
        echo "}"
    fi
}

gen_dep_graph() {
    # Scan all directories of pkg/
    print_head "$1"
    PKGS=$(ls -d pkg/*)
    for pkg in $PKGS; do
        print_single_dep "$1" "$pkg"
        DOCKFILE="$pkg/Dockerfile"
        REMDOCKFILE=false

        if [ ! -e "$DOCKFILE" ]; then
            if [ -e "$pkg/Dockerfile.in" ]; then
                DOCKFILE=$(mktemp)
                $PARSE_PKGS "$pkg/Dockerfile.in" > "$DOCKFILE"
                REMDOCKFILE=true
            else
                continue
            fi
        fi

        deps=$(get_deps "$DOCKFILE")
        if [ "$REMDOCKFILE" = "true" ]; then
            rm "$DOCKFILE"
        fi

        for d in $deps; do
            if [ "$d" = "$pkg" ] || [ "$d" = "/tmp" ]; then
                continue
            else
                print_dep "$1" "$pkg" "$d"
            fi
        done
    done

    # Scan rootfs dependencies
    if [ "$DROOTFS" = "true" ]; then
        for x in images/out/*.yml; do
            ROOTFSDEPS=$(grep "image: lfedge/" < "$x" | sed 's#.* lfedge/eve-\(.*\):.*#pkg/\1#')
            for d in $ROOTFSDEPS; do
                print_dep "$1" "$x" "$d"
            done
        done 2> /dev/null || true
    fi

    print_tail "$1"
}

if [ $# -lt 2 ]; then
    echo "Create dependency packages tree"
    echo
    echo "Use:"
    echo "    $0 [-r] <-i|-m> <output_file>"
    echo
    echo "Options:"
    echo "        -i <output_file> : Generate a PNG image file"
    echo "        -m <output_file> : Generate a Makefile auxiliary file"
    echo "        -r               : Also generates dependencies for rootfs images"
    exit 1
else
    DROOTFS="false"
    while [ $# -gt 0 ]; do
        case "$1" in
            "-i")
                TYPE="IMG"
                PNGFILE=$2
                DOT=$(which dot)
                if [ -z "$DOT" ]; then
                    echo "dot tool not found. Please, install graphviz package."
                    echo
                    exit 1
                fi
                DOTFILE=$(mktemp)
                shift
                shift
            ;;
            "-m")
                TYPE="MK"
                MKFILE=$2
                shift
                shift
            ;;
            "-r")
                DROOTFS="true"
                shift
            ;;
            *)
                echo "$1 : Invalid option"
                exit 1
        esac
    done
fi

if [ "$TYPE" = "IMG" ]; then
    gen_dep_graph "$TYPE" "$DROOTFS" > "$DOTFILE"
    $DOT -Tpng "$DOTFILE" -o "$PNGFILE"
    rm "$DOTFILE"
    echo "Done. Output generated image written to ${PNGFILE}."
else
    gen_dep_graph "$TYPE" "$DROOTFS" > "$MKFILE"
    echo "Done. Output Makefile written to ${MKFILE}."
fi
echo
