// Copyright (c) 2026 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

package displaymgr

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/lf-edge/eve/pkg/pillar/types"
	fileutils "github.com/lf-edge/eve/pkg/pillar/utils/file"
	uuid "github.com/satori/go.uuid"
)

// Placement is one surface-to-connector binding: the compositor fullscreens
// the AppID's surface number Scanout on Connector.
type Placement struct {
	AppID     string
	Scanout   int
	Connector string
	// AppUUID is the application that owns this surface. Carried alongside
	// AppID so callers reporting connector ownership and the compositor
	// rules it derives cannot disagree about who won a contested connector.
	AppUUID uuid.UUID
}

// BuildPlacements flattens the per-application surface configs into the flat,
// deterministic list the compositor consumes.
//
// Ordering is by app-id then scanout so the generated file only changes when
// the placement actually changes — pubsub hands us configs in map order, and
// rewriting the file on every unrelated event would SIGHUP the compositor
// (and flicker every monitor) for nothing.
//
// A connector claimed by two applications is a device-model or controller
// error we cannot resolve here: the first claimant in sorted order keeps it
// and the conflict is returned so the caller can surface it. Silently letting
// the second claimant win would make which app owns a monitor depend on map
// iteration order.
func BuildPlacements(configs []types.DisplaySurfaceConfig) ([]Placement, []error) {
	sorted := make([]types.DisplaySurfaceConfig, len(configs))
	copy(sorted, configs)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].AppID < sorted[j].AppID
	})

	var placements []Placement
	var conflicts []error
	owner := make(map[string]string)
	for _, config := range sorted {
		for i, connector := range config.Connectors {
			if other, taken := owner[connector]; taken {
				conflicts = append(conflicts, fmt.Errorf(
					"connector %s is claimed by both %s and %s; keeping %s",
					connector, other, config.AppID, other))
				continue
			}
			owner[connector] = config.AppID
			placements = append(placements, Placement{
				AppID:     config.AppID,
				Scanout:   i,
				Connector: connector,
				AppUUID:   config.UUIDandVersion.UUID,
			})
		}
	}
	return placements, conflicts
}

// RenderPlacementFile serializes placements into the compositor's placement
// file format: one "<app-id> <scanout> <connector>" record per line, blank
// lines and '#' comments ignored by the reader.
func RenderPlacementFile(placements []Placement) []byte {
	var b strings.Builder
	b.WriteString("# Generated by displaymgr. Do not edit.\n")
	b.WriteString("# <wayland-app-id> <scanout-index> <drm-connector>\n")
	for _, p := range placements {
		fmt.Fprintf(&b, "%s %d %s\n", p.AppID, p.Scanout, p.Connector)
	}
	return []byte(b.String())
}

// WritePlacementFile writes the placement file atomically and reports whether
// the contents changed. An unchanged file means the caller must not signal the
// compositor.
func WritePlacementFile(path string, placements []Placement) (changed bool, err error) {
	contents := RenderPlacementFile(placements)
	if existing, err := os.ReadFile(path); err == nil && string(existing) == string(contents) {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return false, err
	}
	if err := fileutils.WriteRename(path, contents); err != nil {
		return false, err
	}
	return true, nil
}
