# .github/workflows/yetus.yml
name: Apache Yetus (PR Target w/ comments)

on:
    pull_request_target:
        branches:
            - master
            - "[0-9]+.[0-9]+"
            - "[0-9]+.[0-9]+-stable"
            - "feature/*"

permissions:
    contents: read
    pull-requests: write # needed for review/summary comments
    checks: write
    statuses: write
    actions: read
    issues: write

jobs:
    yetus:
        runs-on: ubuntu-24.04
        container:
            image: renezededa/yetus:latest # or ghcr.io/apache/yetus:main
        steps:
            - name: Checkout base repo @ base branch
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  repository: ${{ github.event.pull_request.base.repo.full_name }}
                  ref: ${{ github.event.pull_request.base.ref }}
                  path: src

            - name: Prepare output dir
              run: mkdir -p out

            - name: Run Apache Yetus on PR patch URL
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PATCH_URL: ${{ github.server_url }}/${{ github.event.pull_request.base.repo.full_name }}/pull/${{ github.event.pull_request.number }}.patch
              run: |
                  test-patch \
                    --debug \
                    --robot \
                    --basedir="src" \
                    --patch-dir="out" \
                    --build-tool="nobuild" \
                    --continuous-improvement=true \
                    --console-report-file="out/console.txt" \
                    --brief-report-file="out/brief.txt" \
                    --html-report-file="out/report.html" \
                    --junit-report-xml="out/junit-report.xml" \
                    --plugins="all,-gitlab,-jira" \
                    --excludes=".yetus/excludes.txt" \
                    --blanks-eol-ignore-file=".yetus/blanks-eol.txt" \
                    --blanks-tabs-ignore-file=".yetus/blanks-tabs.txt" \
                    --github-token="${GITHUB_TOKEN}" \
                    --github-repo="${{ github.event.pull_request.base.repo.full_name }}" \
                    --github-base-url="${{ github.server_url }}" \
                    --github-api-url="${{ github.api_url }}" \
                    --github-annotation-limit=50 \
                    --github-status-use-htmlreport=true \
                    --github-write-comment=true \
                    --linecomments=github \
                    --branch="${{ github.event.pull_request.base.ref }}" \
                    --branch-default="${{ github.event.pull_request.base.ref }}" \
                    "${PATCH_URL}"

            - name: Upload Yetus artifacts
              if: ${{ always() }}
              uses: actions/upload-artifact@v4
              with:
                  name: yetus-scan
                  path: out
