# .github/workflows/yetus.yml
name: Apache Yetus

on:
    pull_request_target:
        branches:
            - "master"
            - "[0-9]+.[0-9]+"
            - "[0-9]+.[0-9]+-stable"
            - "feature/*"

permissions:
    contents: read
    pull-requests: write
    checks: write
    statuses: write
    actions: read
    issues: write

jobs:
    yetus:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout PR head (from fork)
              uses: actions/checkout@v4
              with:
                  path: src
                  fetch-depth: 0
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  ref: ${{ github.event.pull_request.head.ref }}

            - name: Prepare dirs
              run: mkdir -p out

            - name: Run Apache Yetus (GitHub PR mode)
              run: |
                  docker run --rm \
                    -e GITHUB_TOKEN="${{ github.token }}" \
                    -e GH_TOKEN="${{ github.token }}" \
                    -e GITHUB_REPOSITORY="${{ github.event.pull_request.base.repo.full_name }}" \
                    -e GITHUB_SERVER_URL="${{ github.server_url }}" \
                    -e GITHUB_API_URL="${{ github.api_url }}" \
                    -e GITHUB_GRAPHQL_URL="${{ github.graphql_url }}" \
                    -e GITHUB_RUN_ID="${{ github.run_id }}" \
                    -e GITHUB_RUN_NUMBER="${{ github.run_number }}" \
                    -e GITHUB_WORKFLOW="${{ github.workflow }}" \
                    -e GITHUB_ACTOR="${{ github.actor }}" \
                    -v "$PWD/src":/workspace \
                    -v "$PWD/out":/out \
                    renezededa/yetus:main \
                    test-patch \
                      --debug \
                      --robot \
                      --basedir=/workspace \
                      --patch-dir=/out \
                      --build-tool=nobuild \
                      --continuous-improvement=true \
                      --console-report-file=/out/console.txt \
                      --brief-report-file=/out/brief.txt \
                      --html-report-file=/out/report.html \
                      --junit-report-xml=/out/junit-report.xml \
                      --plugins=all,-gitlab,-jira \
                      --excludes=.yetus/excludes.txt \
                      --blanks-eol-ignore-file=.yetus/blanks-eol.txt \
                      --blanks-tabs-ignore-file=.yetus/blanks-tabs.txt \
                      --branch="${{ github.event.pull_request.base.ref }}" \
                      --branch-default="${{ github.event.pull_request.base.ref }}" \
                      --github-repo="${{ github.event.pull_request.base.repo.full_name }}" \
                      GH:${{ github.event.pull_request.number }}

            - name: Upload Yetus artifacts
              if: ${{ always() }}
              uses: actions/upload-artifact@v4
              with:
                  name: yetus-scan
                  path: out
