# .github/workflows/yetus.yml
name: Apache Yetus

on:
    pull_request_target:
        branches:
            - master
            - "[0-9]+.[0-9]+"
            - "[0-9]+.[0-9]+-stable"
            - "feature/*"

permissions:
    contents: read
    pull-requests: write
    checks: write
    statuses: write
    actions: read
    issues: write

jobs:
    yetus:
        runs-on: ubuntu-24.04

        # Run steps directly inside the Yetus image (simplest).
        container:
            image: renezededa/yetus:latest
            # or: ghcr.io/apache/yetus:main

        steps:
            # Checkout the *base* repo at the base branch (target of the PR).
            - name: Checkout base repo @ base branch
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  repository: ${{ github.event.pull_request.base.repo.full_name }}
                  ref: ${{ github.event.pull_request.base.ref }}
                  path: src

            - name: Prepare output dir
              run: mkdir -p out

            - name: Run Apache Yetus on PR patch URL
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PATCH_URL: ${{ github.server_url }}/${{ github.event.pull_request.base.repo.full_name }}/pull/${{ github.event.pull_request.number }}.patch
                  # If you prefer to hardcode:
                  # PATCH_URL: https://github.com/rene/eve/pull/${{ github.event.pull_request.number }}.patch
              run: |
                  # Sanity: show what we're testing
                  echo "Repo: ${{ github.event.pull_request.base.repo.full_name }}"
                  echo "Base branch: ${{ github.event.pull_request.base.ref }}"
                  echo "Patch URL: ${PATCH_URL}"

                  # Run Yetus. Last arg is the .patch URL (no GH: mode).
                  test-patch \
                    --debug \
                    --robot \
                    --basedir="src" \
                    --patch-dir="out" \
                    --build-tool="nobuild" \
                    --continuous-improvement=true \
                    --console-report-file="out/console.txt" \
                    --brief-report-file="out/brief.txt" \
                    --html-report-file="out/report.html" \
                    --junit-report-xml="out/junit-report.xml" \
                    --plugins="all,-gitlab,-jira,-ansiblelint,-ant,-bugzilla" \
                    --excludes=".yetus/excludes.txt" \
                    --blanks-eol-ignore-file=".yetus/blanks-eol.txt" \
                    --blanks-tabs-ignore-file=".yetus/blanks-tabs.txt" \
                    --github-token="${GITHUB_TOKEN}" \
                    --github-repo="${{ github.event.pull_request.base.repo.full_name }}" \
                    --branch="${{ github.event.pull_request.base.ref }}" \
                    --branch-default="${{ github.event.pull_request.base.ref }}" \
                    --linecomments=github \
                    --github-annotations-limit=50 \
                    "${PATCH_URL}"

            - name: Upload Yetus artifacts
              if: ${{ always() }}
              uses: actions/upload-artifact@v4
              with:
                  name: yetus-scan
                  path: out
