# Copyright (c) 2025, Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0
#
# NOTE that this is the only workflow that requires access to the
# GitHub token. However, it is safe since in EVE repo itself we
# only trigger this workflow on pull requests and as such making
# it effectively read-only.
# yamllint disable rule:line-length
#   https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
# yamllint enable rule:line-length
---
name: Apache Yetus
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-stable"
      - "feature/*"

jobs:
  yetus:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          path: src
          fetch-depth: 0

      - name: Generate patch locally
        run: |
          cd src
          git diff origin/${{ github.base_ref }}...HEAD > ${{ github.workspace }}/pr.patch

      - name: Yetus
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/apache/yetus:main \
            test-patch \
            --basedir=/workspace/src \
            --patch-dir=/workspace/out \
            --patch-file=/workspace/pr.patch \
            --build-tool=nobuild \
            --continuous-improvement=true \
            --github-token=${{ secrets.GITHUB_TOKEN }} \
            --plugins='all,-asflicense,-author,-findbugs,-gitlab,-jira,-shelldocs' \
            --revive-config=.revive.toml \
            --brief-report-file=/workspace/out/brief.txt \
            --console-report-file=/workspace/out/console.txt \
            --html-report-file=/workspace/out/report.html \
            --junit-report-xml=/workspace/out/junit-report.xml \
            --ignore-unknown-options=true \
            --pylint-requirements=true \
            --report-unknown-options=false

      - name: Store Yetus artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
        with:
          name: 'yetus-scan'
          path: ${{ github.workspace }}/out
