# .github/workflows/yetus.yml
name: Apache Yetus (PR Target w/ comments)

on:
    pull_request_target:
        branches:
            - master
            - "[0-9]+.[0-9]+"
            - "[0-9]+.[0-9]+-stable"
            - "feature/*"

permissions:
    contents: read
    pull-requests: write # needed for review/summary comments
    checks: write
    statuses: write
    actions: read
    issues: write

jobs:
    yetus:
        runs-on: ubuntu-24.04
        container:
            image: ghcr.io/apache/yetus:0.15.1 # recent, known-good
        steps:
            - uses: actions/checkout@v4
              with:
                  repository: ${{ github.event.pull_request.base.repo.full_name }}
                  ref: ${{ github.event.pull_request.base.ref }}
                  path: src

            - run: mkdir -p out

            - name: "Run Yetus (GH: mode)"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  test-patch \
                    --debug \
                    --robot \
                    --basedir=src \
                    --patch-dir=out \
                    --build-tool=nobuild \
                    --github-repo="${{ github.event.pull_request.base.repo.full_name }}" \
                    --github-token="${GITHUB_TOKEN}" \
                    --github-base-url="${{ github.server_url }}" \
                    --github-api-url="${{ github.api_url }}" \
                    --linecomments=github \
                    --github-annotation-limit=50 \
                    --branch="${{ github.event.pull_request.base.ref }}" \
                    --branch-default="${{ github.event.pull_request.base.ref }}" \
                    GH:${{ github.event.pull_request.number }}
