# .github/workflows/yetus.yml
name: Apache Yetus

on:
    pull_request_target:
        branches:
            - master
            - "[0-9]+.[0-9]+"
            - "[0-9]+.[0-9]+-stable"
            - "feature/*"

permissions:
    contents: read
    pull-requests: write
    checks: write
    statuses: write
    actions: read
    issues: write

jobs:
    yetus:
        runs-on: ubuntu-24.04

        # Run all steps directly inside the Yetus image (no docker-in-docker)
        container:
            # Use your image or switch to ghcr.io/apache/yetus:main
            image: renezededa/yetus:eve-latest

        steps:
            - name: Checkout PR head (from fork)
              uses: actions/checkout@v4
              with:
                  path: src
                  fetch-depth: 0
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  ref: ${{ github.event.pull_request.head.ref }}

            - name: Prepare output dir
              run: mkdir -p out

            - name: Run Apache Yetus (GitHub PR mode)
              env:
                  # passed to Yetus for GitHub API access
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  set -euxo pipefail

                  # Optional: show where we are (GitHub mounts the workspace automatically)
                  pwd
                  ls -la

                  # Run Yetus directly (no docker run). Everything is inside the container already.
                  test-patch \
                    --debug \
                    --robot \
                    --basedir="src" \
                    --patch-dir="out" \
                    --build-tool="nobuild" \
                    --continuous-improvement=true \
                    --console-report-file="out/console.txt" \
                    --brief-report-file="out/brief.txt" \
                    --html-report-file="out/report.html" \
                    --junit-report-xml="out/junit-report.xml" \
                    --plugins="all,-gitlab,-jira" \
                    --excludes=".yetus/excludes.txt" \
                    --blanks-eol-ignore-file=".yetus/blanks-eol.txt" \
                    --blanks-tabs-ignore-file=".yetus/blanks-tabs.txt" \
                    --github-token="${GITHUB_TOKEN}" \
                    --github-repo="${{ github.event.pull_request.base.repo.full_name }}" \
                    --branch="${{ github.event.pull_request.base.ref }}" \
                    --branch-default="${{ github.event.pull_request.base.ref }}" \
                    GH:${{ github.event.pull_request.number }}

            - name: Upload Yetus artifacts
              if: ${{ always() }}
              uses: actions/upload-artifact@v4
              with:
                  name: yetus-scan
                  path: out
